proj_dirs:
  lib_pages:  "extra_img_1851_pages"
  ch_raw:     "chapters_01_raw"
  ch_clean:   "chapters_02_clean"
  ch_patched: "chapters_03_patched"
  ch_xhtml:   "chapters_04_xhtml"
  css_dir:    "css"
  custom_dir: "custom"
  img_dir:    "images"
  custom_img: "custom_img_sm" # for custom images to insert into EPUB according to insert_img.csv
epub_dirs:
  book_dir:   "EPUB-{}" # {}, for separate epub for footnotes and hyperlinks
  meta_dir:   "META_INF"
  oeb_dir:    "OEBPS"
  css_dir:    "css"
  img_dir:    "images"
  epub_book:  "Moby-Dick [Power, {}] - Herman Melville.epub" # {}, for separate epub for footnotes and hyperlinks
exe_mode:
  version:    "2026.01.10"
# uuid:       "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  uuid:       "0abcdef0-2026-0104-0ba0-0dd003151967"
  debugging:  False
  epub_ref:   "foot" # foot or link. For e-readers that don't support epub:type="footnotes", use create <a> links.
ext_resource:
  base_url:   "http://www.powermobydick.com/"
  lib_url:    "https://ia800205.us.archive.org/BookReader/BookReaderImages.php?zip=/32/items/mobydickorwhale01melv/mobydickorwhale01melv_jp2.zip&file=mobydickorwhale01melv_jp2/mobydickorwhale01melv_{image:04d}.jp2&id=mobydickorwhale01melv"
